// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXGZnZ61zD9lMwAjfDYXOTm956kzLD3Sg',
    appId: '1:467631095706:web:e90ffbef35d30b1c938423',
    messagingSenderId: '467631095706',
    projectId: 'meetspacepro',
    authDomain: 'meetspacepro.firebaseapp.com',
    storageBucket: 'meetspacepro.firebasestorage.app',
    measurementId: 'G-V96T07LXYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufZ9vD7ezl4f-QJEodUDvEAdW4FyvfpI',
    appId: '1:467631095706:android:e4c222d2468556c9938423',
    messagingSenderId: '467631095706',
    projectId: 'meetspacepro',
    storageBucket: 'meetspacepro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-BIYUc0xt6_RF1hXD9y5UsjwBfI858qc',
    appId: '1:467631095706:ios:c5b7d2cb58143a4b938423',
    messagingSenderId: '467631095706',
    projectId: 'meetspacepro',
    storageBucket: 'meetspacepro.firebasestorage.app',
    androidClientId: '467631095706-c5gcpfc1n6b1mnrqqjvpd0ti4i1kkmdd.apps.googleusercontent.com',
    iosClientId: '467631095706-4j7rptvn2qupre6pj1aucoc36m3kcsvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-BIYUc0xt6_RF1hXD9y5UsjwBfI858qc',
    appId: '1:467631095706:ios:c5b7d2cb58143a4b938423',
    messagingSenderId: '467631095706',
    projectId: 'meetspacepro',
    storageBucket: 'meetspacepro.firebasestorage.app',
    androidClientId: '467631095706-c5gcpfc1n6b1mnrqqjvpd0ti4i1kkmdd.apps.googleusercontent.com',
    iosClientId: '467631095706-4j7rptvn2qupre6pj1aucoc36m3kcsvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXGZnZ61zD9lMwAjfDYXOTm956kzLD3Sg',
    appId: '1:467631095706:web:f523bb0c1c68aa2a938423',
    messagingSenderId: '467631095706',
    projectId: 'meetspacepro',
    authDomain: 'meetspacepro.firebaseapp.com',
    storageBucket: 'meetspacepro.firebasestorage.app',
    measurementId: 'G-TR84YPMZP7',
  );
}
